services:
  mongodb:
    image: mongo:7
    container_name: nestjs-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
      MONGO_INITDB_DATABASE: testing
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
